### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by WebVeteran**
Added the missing LINK icon to the CSS file.
Added YouTube 18px icons.

### CODE REVIEW

**Comment by commadelimited** [comment]
Great. I've actually already added the link icon into the set, but I don't have Youtube. Would you mind rebasing against the master repo and resubmitting your pull request?

**Comment by WebVeteran** [comment]
Done. It looks like I can't resubmit the pull request. I'm not a wiz at github yet =). But I think my new commits are here for you to see.

**Comment by commadelimited** [comment]
You're golden now. Thanks for your submission.

**Comment by WebVeteran** [comment]
My pleasure - thanks for publishing the springboard =)

**Pull request merged**
