### PR TITLE
Added Missing Bars Icon (jQuery Mobile 1.3.1)

### PR DESCRIPTION
**Pull request by XjSv**
Added Missing Bars Icon both 18px and 36px.
Also added CSS for the Chain Icon.
(Tested with jQuery Mobile 1.3.1)

### CODE REVIEW

**Comment by diniremix** [comment]
Thank you very much **XjSv** for changes, although in **jQueryMobile 1.3.0** also presents the same problem as the icon **bars** not charging.


The code below


Thanks!, apologize for the translation.

P.D.
Can you fix for font-awesome?

**Comment by XjSv** [comment]
The example on the screen shot is using the font correct? I will have to the same for there also. It works for me when using the 18px and 36px images.

**Comment by XjSv** [comment]
I believe it is fixed now. Added some missing CSS. I did not however touch the font stuff.

**Comment by eug48** [comment]
Thanks for working on this @XjSv ! I've noticed that other icons have been changed too, is that the same as in jQuery Mobile? Also the wrench icon looks fairly different.

**Comment by XjSv** [comment]
Yes I believe it is. I downloaded the latest copy of jQuery Mobile before I made the changes. I also used your existing PSD's to make the changes on. My mistake if it did not come out correct.

**Comment by eug48** [comment]
It looks like the PNG isn't generated directly from the PSD..? I'm not totally sure as I haven't worked on this project. Maybe you would need to edit the png separately.

**Comment by XjSv** [comment]
LOL I am sorry I was working on like 3 things at the same time when I replied. I assumed I was speaking to the repo author. Again my mistake. 

As for the changes:
Im not sure if these are the latest PSD's. Maybe I'm not understanding the PSD file. I'm not sure how one could have exported both white and black versions of the images from these PSD's. Only some layers had 'Color Overlays' effects on them to flip the color from black to white or vice versa.

Also in the 'icons-18-pack.psd' the wrench icon is different without any modifications. Am I missing layers?
Another thing about the 'icons-18-pack.psd' is that the check boxes and radio buttons background is not transparent. 

I re-exported the images from the psd files once again. In the PSD's the check boxes and radio buttons should be identical except size. 

I have attached some screen shots with my changes demoed from an iPhone 5 & Firefox with user agent changed (using 36px and 18px images respectively). It appears fine. 
I am using: jQuery Mobile 1.3.1. 

##### Unmodified PSD file (Downloaded from: https://github.com/commadelimited/jQuery-Mobile-Icon-Pack/archive/master.zip):

image 001

##### Screenshots (Firefox [iOS Safari 4.1.1 User Agent]):

image 003
image 002
image 004

##### Screenshots (iPhone 5):

img_1142
img_1143

**Comment by eug48** [comment]
lol, yeah, I'm just someone who uses this great icon pack and would like the bar icon to be merged :)

Take a look at the File Changes tab at the top of this pull request, specifically icons-18-black-pack.png - try the "swipe" comparison. See how many of the icons are changing even though this patch is only supposed to add the bar icon? @commadelimited might want the other icons kept as they are. icons-36-black-pack.png looks okay - only the bar icon is added.

**Comment by commadelimited** [comment]
Hey @XjSv, thanks for your hard work on this. I recently updated the icon pack which means your PR can't be automatically merged. Would you mind rebasing it against master then resubmitting?

**Comment by XjSv** [comment]
Yes sure sorry for the delay. Ill try to do it by tomorrow.

**Comment by commadelimited** [comment]
The stacked bar icon was added in #41.

**Pull request closed without merging**
