### PR TITLE
Adding support for ui-icon-nodisc

### PR DESCRIPTION
**Pull request by jcpmmx**
Using jQuery Mobile 1.3.1 and jQuery Mobile Icon Pack with Font Awesome 3.2

### CODE REVIEW

**Comment by commadelimited** [comment]
Thanks!

**Comment by jcpmmx** [comment]
@commadelimited, the merge went bad... '<<<<<<< HEAD' was included

**Comment by commadelimited** [comment]
Interesting. I didn't see any merge conflicts. I'll repush.

**Comment by commadelimited** [comment]
Okay. Should be fixed.

**Pull request merged**
